version: "3.5"

services:
  web:
    build: .
    command: bash -c "python manage.py createcachetable && python /code/manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
